name: Staging deployment

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited
    branches:
      - staging

jobs:
  heroku:
    runs-on: ubuntu-latest
    name: Heroku deployment
    steps:
      - uses: actions/checkout@v3
      - name: Branch name
        run: echo running on branch ${GITHUB_REF}
      - name: Add api remote origin
        run: git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_STAGING }}.git
      - name: Deploy api to Heroku
        run: git push heroku `git subtree split --prefix backend -b ${GITHUB_REF}`:refs/heads/master --force
