name: Test workflow

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited
    branches:
      - staging

# jobs:
  # backend_test:
  #   runs-on: ubuntu-latest
  #   name: Backend test
  #   defaults:
  #     run:
  #       working-directory: ./backend
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Set up Go
  #       uses: actions/setup-go@v3
  #       with:
  #         go-version: 1.19
  #     - name: Install dependencies
  #       run: go get .
  #     - name: Build
  #       run: go build -v ./...

  #     - name: Run Test  # Pass the `coverage.out` output to this action
  #       run: go test -v ./controllers/... -covermode count -coverprofile coverage.out

  #     - name: Analyze with SonarCloud
  #       uses: sonarsource/sonarcloud-github-action@master
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  # heroku:
  #   needs: backend_test
  #   runs-on: ubuntu-latest
  #   name: Heroku deployment
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Branch name
  #       run: echo running on branch ${{ github.event.pull_request.head.sha }}
  #     - name: Add api remote origin
  #       run: git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_STAGING }}.git
  #     - name: Deploy api to Heroku
  #       run: git push heroku `git subtree split --prefix backend ${{ github.event.pull_request.head.sha }}`:refs/heads/master --force