name: Test

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited
    branches:
      - master
      - staging

jobs:
  backend_test:
    runs-on: ubuntu-latest
    name: Backend test
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -v ./...

      - name: Run Test  # Pass the `coverage.out` output to this action
        run: go test -v ./controllers/... -covermode count -coverprofile coverage.out
          
      - name: Run Tool Cover Test
        run: go tool cover -func coverage.out -o coverage.out

      - name: ls
        run: ls -a

      - name: Go Coverage Badge
        uses: tj-actions/coverage-badge-go@v1
        with:
          filename: coverage.out

      - name: Verify Changed files
        uses: tj-actions/verify-changed-files@v8.1
        id: verify-changed-files
        with:
          files: README.md

      - name: Create Pull Request
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        uses: peter-evans/create-pull-request@v3
        with:
          base: "main"
          title: "chore: updated coverage Badge"
          branch: "chore/update-coverage"
          commit-message: "chore: updated coverage Badge"
          body: "updated coverage Badge"
          token: ${{ secrets.GITHUB_TOKEN }}

  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
